### ISSUE TITLE
Error Stacktrace

### ISSUE THREAD

**Issue by rcky** [eventEmitter/ee-class#1]
It would be great to have a correct stack trace for subclasses of `Error` _e.g._ by automated application of

```
Error.captureStackTrace(this, arguments.callee);
```

**Comment by linaGirl** [comment]
This method is only available in v8. The class implementation is currently compatible with most of the ecma 5 compatible engines. I wish to keep it that way. (I use it sometimes in the browser)

The arguments object is deprecated.

**Comment by linaGirl** [comment]
stopping to enhance this module for node.js since ecma 2015 classes provide the same functionality at approximately the same speed as this module. The development  focuses now browsers until they have full class support.
