### ISSUE TITLE
Confusing npm test script behavior

### ISSUE THREAD

**Issue by pdehaan** [eventEmitter/ee-class#5]
Currently, the [package.json](https://github.com/eventEmitter/ee-class/blob/ebff8176e61b8eb7cfa0484143ded8e3e662c978/package.json#L24-L29) file has two `scripts` fields, both with different `test` scripts.

``` js
    , "scripts": {
        "test"                      : "node test.js"
    }
     , "scripts": {
        "test"                      : "./node_modules/mocha/bin/mocha --reporter spec"
    }
```

**Comment by linaGirl** [comment]
thanks!

fixed in https://github.com/eventEmitter/ee-class/commit/6aae693ba0e80441718ed2d80c83bc1259679547
